# Generated by Django 4.2.16 on 2026-06-24 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('CLASS', 'CLASS'), ('STUDENT', 'STUDENT'), ('ASSESSMENT', 'ASSESSMENT'), ('GROUP', 'GROUP')], max_length=30)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('metrics', models.JSONField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='courses.coursesection')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='courses.student')),
            ],
            options={
                'db_table': 'metric_snapshot',
                'indexes': [models.Index(fields=['section', 'snapshot_type', '-calculated_at'], name='metric_snap_section_661f83_idx'), models.Index(fields=['student', '-calculated_at'], name='metric_snap_student_f99507_idx')],
            },
        ),
    ]
