# Generated by Django 4.2.16 on 2026-06-24 22:22

import apps.reports_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('CLASS_SUMMARY', 'CLASS_SUMMARY'), ('RISK_LIST', 'RISK_LIST'), ('COMPARISON', 'COMPARISON')], max_length=30)),
                ('parameters', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.reports_app.models._default_expires_at)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='courses.coursesection')),
            ],
            options={
                'db_table': 'report_export',
                'indexes': [models.Index(fields=['section', '-created_at'], name='report_expo_section_fb7827_idx'), models.Index(fields=['status'], name='report_expo_status_ca49ef_idx')],
            },
        ),
    ]
