# Generated by Django 4.2.16 on 2026-06-24 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('term', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course',
                'unique_together': {('code', 'term', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ARCHIVED', 'ARCHIVED'), ('HIDDEN', 'HIDDEN')], default='ACTIVE', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taught_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_section',
                'unique_together': {('course', 'section_code')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('anonymized_code', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('QUIZ', 'QUIZ'), ('LAB', 'LAB'), ('ASSIGNMENT', 'ASSIGNMENT'), ('MIDTERM', 'MIDTERM'), ('FINAL', 'FINAL'), ('PARTICIPATION', 'PARTICIPATION')], max_length=30)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('week_no', models.SmallIntegerField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.coursesection')),
            ],
            options={
                'db_table': 'assessment',
            },
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('activity_type', models.CharField(choices=[('ATTENDANCE', 'ATTENDANCE'), ('PARTICIPATION', 'PARTICIPATION'), ('LOGIN', 'LOGIN'), ('OTHER', 'OTHER')], max_length=30)),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursesection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.student')),
            ],
            options={
                'db_table': 'student_activity',
                'indexes': [models.Index(fields=['section', 'student', 'activity_date'], name='student_act_section_30a2b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DROPPED', 'DROPPED'), ('COMPLETED', 'COMPLETED')], default='ACTIVE', max_length=20)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.coursesection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.student')),
            ],
            options={
                'db_table': 'enrollment',
                'unique_together': {('section', 'student')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submission_status', models.CharField(blank=True, max_length=20, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='courses.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='courses.student')),
            ],
            options={
                'db_table': 'assessment_score',
                'unique_together': {('assessment', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['section', 'type', 'week_no'], name='assessment_section_18777a_idx'),
        ),
    ]
