# Generated by Django 4.2.16 on 2026-06-24 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('import_type', models.CharField(choices=[('ROSTER', 'ROSTER'), ('SCORE', 'SCORE'), ('ACTIVITY', 'ACTIVITY'), ('MIXED', 'MIXED')], max_length=30)),
                ('status', models.CharField(choices=[('UPLOADED', 'UPLOADED'), ('VALIDATING', 'VALIDATING'), ('SUCCESS', 'SUCCESS'), ('PARTIAL', 'PARTIAL'), ('FAILED', 'FAILED')], default='UPLOADED', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='courses.coursesection')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_batch',
                'indexes': [models.Index(fields=['section', '-created_at'], name='import_batc_section_6e3369_idx'), models.Index(fields=['status'], name='import_batc_status_ad7ea1_idx')],
            },
        ),
    ]
